config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'carts/show'

  resources :items
  root 'items#index'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
resource :cart, only: [:show] do
    put 'add/:item_id', to: 'carts#add', as: :add_to
    put 'remove/:item_id', to: 'carts#remove', as: :remove_from
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
	def cart_action(current_user_id)
  if $redis.sismember "cart#{current_user_id}", id
    "Remove from"
  else
    "Add to"
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

def cart_count #método de contagem
    $redis.scard "cart#{id}"
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_items = Item.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:item_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:item_id]
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @cart_action = @item.cart_action current_user.try :id
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :release_date, :img_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>Meus Livros</h4>
    <p class="mb0"> Você selecionou <span class="cart-count"><%=current_user.cart_count%></span> livros!</p>
  </div>

  <% @cart_items.each do |item|%>
  <div data-equalizer class="cart-item large-12 column mb1" >
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to item do%>
        <img class="radius-l1" src= '<%= item.img_url %>'>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= item.nome %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to "" , data: {targetUrl: remove_from_cart_path(item)} do%>
        <i class="right">X</i>
      <%end%>
      <h4 class="scale">R$ <%= item.price %></h4>
    </div>
    <br>
  </div>
  <br>
  <br>
  <br>
  <%end%>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.date_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<html class="no-js" lang="en">
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">

  </head>
    <body>

      <div id="slideShowImages">
     <img src="https://1.bp.blogspot.com/-1nwzZ0aA79Q/V3h1EDBnj1I/AAAAAAAABQA/HxrLXqkgbOA_wNMl6S6cVEPNE1oIpgkYQCLcB/s1600/comoerabanner_2000x750.jpg" alt="Slide 1" />
     <img src="https://4.bp.blogspot.com/-iLKI5-M0g-s/V3h0_bUW16I/AAAAAAAABP4/hA2lbjj9KKEfVeiiXQN8viFQ3QKGn8qRQCLcB/s1600/culpaestrelasbanner_2000x750.jpg" alt="Slide 2" />
     <img src="https://2.bp.blogspot.com/-eiIiaGpdtxU/V3h1B1FsKuI/AAAAAAAABP8/4Th6wdATa8A_PwEGuEkQ6hBzmTpzQ0fUQCLcB/s1600/depoisdevocebanner_2000x750.jpg" alt="Slide 3" />
     <img src="https://1.bp.blogspot.com/-sIQHWICZTXA/V3h11etaheI/AAAAAAAABQE/1PBhRIQa91IibHXvqRiohukGkWMYw5tywCLcB/s1600/crepusculobanner_2000x750.jpg" alt="Slide 4" />
  </div>
    <script src="app/javascripts/slideShow.js"></script>

    <div class="row column text-center">
      <br>
      <hr>
      <h2>Novos Livros</h2>
      <hr>
    </div>

    <div class="row small-up-2 large-up-4">
        <% @items.each do |item| %>
      <div class="column">
        <%= link_to item do %>
        <img class="thumbnail" src="<%= item.img_url %>">
        <h5><%=item.nome%></h5>
        <p>R$ <%= item.price %></p>
      </div>
      <% end %>
        <% end %>
    </div>

</html>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<!doctype html>
<html class="no-js" lang="en">
<script src="app/javascripts/slideShow.js"></script>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">

  </head>
  <body>

    <br>
    <!-- You can now combine a row and column if you just need a 12 column row -->
    <div class="row columns">
      <nav aria-label="You are here:" role="navigation">
        <ul class="breadcrumbs">
          <li><a href="http://localhost:3000/items/">Início</a></li>

        </ul>
      </nav>
    </div>

    <div style="margin: 15px ">
              <img class="thumbnail" src="<%=@item.img_url%>"  style="width: 390px; height: 300px; margin: 15px; float:left; " />
              <h3><%=@item.nome%></h3>
              <h6><%=@item.release_date%></h6>
              <p><%=@item.description%></p>
          </div>

          <label>Preço
          <h2>R$ <%=@item.price%></h2>
          </label>

        <div class="row">
          <div class="small-3 columns">

          </div>
          <div class="small-9 columns">

          </div>
        </div>

         <div class="row" style="float:right; margin: 13px ">
          <%if signed_in?%>
            <%=link_to "", class: " button", data: {target: @cart_action, addUrl: add_to_cart_path(@item), removeUrl: remove_from_cart_path(@item)} do%>
              <span><%=@cart_action%></span> 
            <%end%>
          <%end%>
        </div>
        <br>
        <br>
        <br>

        <div class="small secondary button-group" style="float:right; margin: 8px">
            <a href="https://www.facebook.com/lojadelivrosrenataegaby/" class="button">Facebook</a>
            <a href="https://twitter.com/LojaDeLivrosRG" class="button">Twitter</a>
          </div>
        </div>
    </div>
    <br>
    <br>


    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>

app/views/layouts/_header.html.erb
<div class="row">

    <a href="/">
    <div class="small-12 medium-4 large-6 columns namelogo">
        <ul class="left button-group">
          <li><%= image_tag("capy.png", size: "16x10", alt: "Edit Entry")%></li>
          <li margin-left="10px"><h1 > Capibara</h1></li>
        </ul>
    </div>
    </a>
    
  <div class="small-12 medium-8 large-6 columns">
    <div class="nav-bar">
      <ul class="button-group">
        <%if signed_in?%>
          <li>
            <%= link_to cart_path, class:"button" do%>
              My Cart
              (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.email, edit_user_registration_path, class: "button"%></li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete, class: "button"%></li>
        <%else%>
          <li><%=link_to "Register", new_user_registration_path, class: "button"%></li>
          <li><%=link_to "Login", new_user_session_path, class: "button"%></li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <title><%= content_for?(:title) ? yield(:title) : "Loja de Livros Renata e Gaby" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

<html class="no-js" lang="en">

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
  </head>
  <body>

    <!-- Start Top Bar -->
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li><a href="http://localhost:3000/items"><img src="  https://3.bp.blogspot.com/-AzYeOgqcDAc/V3RWbpphjYI/AAAAAAAABOk/xJVmLL_Vib8dcJ-YWQyFtvXbjMFFaBa-wCLcB/s1600/Logo-Loja.jpeg"></a></li>
          <li><a href="https://gitlab.com/gabygama_22/EP3OO_Teste">GitLab</a></li>
          <li><a href="#">YouTube</a></li>
        </ul>
      </div>

      <div class="top-bar-right">
        <ul class="menu">

        <!-- adaptado -->
<%if signed_in?%>
          <!-- My cart -->
           <li>
            <%= link_to cart_path, class:"button" do%>
              Meus Livros
              (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.email, edit_user_registration_path, class: "button"%></li>
          <li><%=link_to "Sair", destroy_user_session_path, method: :delete, class: "button"%></li>
        <%else%>
          <li><%=link_to "Entrar", new_user_session_path, class: "button"%></li>
        <li><%=link_to "Crie uma conta", new_user_registration_path, class: "button"%></li>
        <li><%=link_to "Admin", href="http://localhost:3000/admin/login", class: "button"%></li>
        <%end%>
      <!-- fim de My Cart -->

        </ul>
      </div>
    </div>
    <!-- End Top Bar -->

  <%= yield %>

    <div class="callout secondary">
      <div class="row">
        <div class="large-4 columns">
          <h5>Loja Virtual de Livros</h5>
          <p>Projeto da disciplina Orientação a Objetos 1/2016 desenvolvido por Gabriela e Renata.</p>
          <p>UnB - FGA</p>
        </div>
        <div class="large-3 large-offset-2 columns">
          <ul class="menu vertical">
          </ul>
        </div>
        <div class="large-3 columns">
          <ul class="menu vertical">
            <li><a href="https://gitlab.com/gabygama_22/EP3OO_Teste">GitLab</a></li>
            <li><a href="#">YouTube</a></li>
          </ul>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>

    <script>
      $(document).foundation();
      <%= javascript_include_tag "application" %>
    </script>

</html>

  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br/>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar-se", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu a senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu instruções de confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu instruções de desbloqueio?", new_unlock_path(resource_name) %> <br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Logar com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>